### ISSUE TITLE
Create a script or test to ensure titles following matching format

### ISSUE THREAD

**Issue by BrooklinJazz** [DockYard-Academy/beta_curriculum#104]

**Comment by BrooklinJazz** [comment]
All titles (## Title Example) in .livemd files should use title case

**Comment by miguelbermudez** [comment]
Do you mean like a shell script or a `.exs` file?

**Comment by BrooklinJazz** [comment]
I think a `.exs` file or test would be most appropriate.

**Comment by miguelbermudez** [comment]
I think I can do this!

**Comment by BrooklinJazz** [comment]
Awesome! Let me know if you want any clarification. I'm also happy to pair program with you at any point - have fun!

**Comment by BrooklinJazz** [comment]
Also there's an existing test in `utils_test.exs` for finding `TestedCell.Control.show_editors()` that you might take inspiration from.

**Comment by miguelbermudez** [comment]
My first attempt was to just to read the contents of the file line-by-line, filter headlines and determine if those headlines were in titlecase. Unfortunately, I hit an issue with [hashes also being in code fences](https://github.com/DockYard-Academy/beta_curriculum/blob/7773178ea60f391bbd58468d71e58608777660b3/exercises/battle_map.livemd?plain=1#L93). Not sure how to get around that. 

I had an idea about parsing `livemd` files as Livebooks does. Turns out there is a helpful and wonderfully named module called [Livebook.LiveMarkdown.MarkdownHelpers](https://github.com/livebook-dev/livebook/blob/920f70817efbacbb160483af895293f9fb43717d/lib/livebook/live_markdown/markdown_helpers.ex). If I could work on the AST instead of what I was doing before it would be easier to just get `H` tags. So based on what Livebook does [here](https://github.com/livebook-dev/livebook/blob/5476fd001d13db902c7f965707aa27599a30cd34/lib/livebook/live_markdown/import.ex#L6), I was able to just get headlines and work on them.  I had to add Livebook and Poison as a dependency to access to module though. (Happy to discuss that part)

[I have a branch up with the test](https://github.com/miguelbermudez/beta_curriculum/commit/30cd2ea510b854cdfb5ed96f1f3dd18d68f52560).  I also have a commit that fixes all the headlines but wanted to make sure you're ok with this approach before pushing that up.

**Comment by BrooklinJazz** [comment]
Can you help me understand the hash issue?

I think we only need to format heading 3s (and maybe 2s) which have 2-3 hashes. 

Does some regex such as `/#/#\w+` not find all heading 2s and 3s?

**Comment by BrooklinJazz** [comment]
Can you help me understand the hash issue?

I think we only need to format heading 3s (and maybe 2s) which have 2-3 hashes. 

Does some regex such as `/#/#\w+` not find all heading 2s and 3s?

**Comment by BrooklinJazz** [comment]
I'm happy with the approach if it works!

**Comment by miguelbermudez** [comment]
> Can you help me understand the hash issue?

I was looking at all headlines so I was getting tripped up with elixir comments in code fences. The test was checking them if they were in titlecase.  If you wanted to check H1s I'm not sure how to avoid code fences without using the AST. 

If the goal is to just check H2 and H3's the line-by-line check would work:
```elixir
File.read!(f)
      |> String.split("\n", trim: true)
      |> Enum.map(fn line ->
        is_title = String.match?(line, ~r/^#{2,3}.*/)
        if is_title do ...
``` 

On another note, is there an easier way to check for titlecase? The regex's I was coming up with are getting unwieldy. They work but I keep thinking there's got to be a better way, especially when you get to articles/prepositions , single word titles, titles that begin with an article or preposition, etc...

**Comment by BrooklinJazz** [comment]
If you've already put the work in to catch all titles using AST then that's awesome! No need to undo that work.

H1s are only ever at the top of the file, so maybe in hindsight we could have used that to check them, or ignore them since they are easy to see manually at a glance.

**Comment by BrooklinJazz** [comment]
What about just grabbing all the words in the title, then capitalizing them. `/w+`

Then on a second pass we can check for specific non capitalized words (on, and, etc) and lowercase them.

**Comment by miguelbermudez** [comment]
> What about just grabbing all the words in the title, then capitalizing them. `/w+`

Sounds good, I updated the branch and made a PR #260.
