### ISSUE TITLE
fix state tree diagram

### ISSUE THREAD

**Issue by threetriangles** [DockYard-Academy/beta_curriculum#317]
![SCR-20220906-jrk](https://user-images.githubusercontent.com/106404756/188708823-c3cdcfef-fa29-4899-a0af-5821a9df00d7.png)

**Comment by BrooklinJazz** [comment]
We need to modify the state diagram so that `Player2` is connected to the second `State` box in the diagram. This should be a simple adjustment if anyone would like to make their first commit :) It's open to anyone though!

I'm happy to walk folks through the process of contributing. Just message below if you're interested.
