### ISSUE TITLE
Code cell not updating properly.

### ISSUE THREAD

**Issue by Billboz** [DockYard-Academy/beta_curriculum#325]
**Describe the issue**
On the "Fun Formulas" page the code cells receive input and appear to be correct but when processed the error shows code that was not input.

**Reproduction Steps (If Applicable)**
1. Go to the 'Fun Formulas' page
2. Click on the 'Percentage' Code cell
3. Enter the correct answer

**Expected behavior**
A passing test.

**Screenshots**
![Screen Shot 2022-09-10 at 11 08 19 AM](https://user-images.githubusercontent.com/2127099/189500499-509cff51-2ef2-487e-85b1-7991163a0fec.png)

**Comment by Billboz** [comment]
The code cells on the next page are displaying the same behavior.

![Screen Shot 2022-09-10 at 6 06 46 PM](https://user-images.githubusercontent.com/2127099/189503378-94f42542-f64c-45e5-8bdc-8736361f313b.png)

**Comment by BrooklinJazz** [comment]
Issue was specific to Livebook Desktop. We believe it's related to this issue here: https://github.com/livebook-dev/livebook/issues/1399

@Billboz and I sat down trying to fix this, but seems like it's on the Livebook side. We resolved the problem by installing livebook on the command line. If anyone else experiences this please let me know!
