### ISSUE TITLE
Tuples: Collections or not collections?

### ISSUE THREAD

**Issue by BigSpaces** [DockYard-Academy/beta_curriculum#392]
Hello Brook,

In the non-enumerables module, you mention that tuples are not collections.

I was checking here: https://elixirschool.com/en/lessons/basics/collections

...and it says they are.

What's the "source of truth"?

Thanks

**Comment by BigSpaces** [comment]
I didn't mean to use the issues as a place to raise a doubt. I meant it as a way to double-check the content of that page to avoid confusion in students. Sorry for not being clear above.

**Comment by BrooklinJazz** [comment]
This is a great use of issues. Thank you for bringing this up, I think I can improve the material to make this more clear.
 
 Tuples are not enumerable (meaning they don't work with the `Enum` module),
 
 > The functions in this module that add and remove elements from tuples are rarely used in practice, as they typically imply tuples are being used as collections. To append to a tuple, it is preferable to extract the elements from the old tuple with pattern matching, and then create a new tuple:
>  https://hexdocs.pm/elixir/1.12/Tuple.html
 
 Another interesting conversation around the topic.
 
 https://stackoverflow.com/questions/41334109/why-tuples-are-not-enumerable-in-elixir
 
 
 I think that we should clarify the lesson to say they are not enumerable, rather than saying they are not collections.
 
 They are not intended to be used as collections, however, I'm honestly not sure if they are "technically not collections" and can't find anything to confirm this. So to make this more accurate, we should change the wording to say they are "not enumberable" rather than "not collections".

**Comment by BigSpaces** [comment]
Thank you, Brook. 

I appreciate you taking the time to unpack this one for me in the midst of a very busy schedule and workload.

When I went to the stackoverflow discussion to dive deeper into ti, I had this type of experience: https://youtu.be/LKCi0gDF_d8?t=15

It is like I am reading ancient Greek still :D  To be expected at this point, I guess.

Looking forward to continuing the process today.


Jon
